<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRc3yf2y\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRc3yf2y/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerRc3yf2y.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerRc3yf2y\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerRc3yf2y\appProdProjectContainer();
