<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\Utils\Bells' shared autowired service.

include_once $this->targetDirs[3].'\\src\\AppBundle\\Utils\\Bells.php';

return $this->services['AppBundle\Utils\Bells'] = new \AppBundle\Utils\Bells();
