<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.obgpexm' shared service.

return $this->services['service_locator.obgpexm'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('bell' => function () {
    $f = function (\AppBundle\Utils\Bells $v = null) { return $v; }; return $f(${($_ = isset($this->services['AppBundle\Utils\Bells']) ? $this->services['AppBundle\Utils\Bells'] : $this->services['AppBundle\Utils\Bells'] = new \AppBundle\Utils\Bells()) && false ?: '_'});
}));
